#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Cheetah
Version  : 2.4.4
Release  : 23
URL      : http://pypi.debian.net/Cheetah/Cheetah-2.4.4.tar.gz
Source0  : http://pypi.debian.net/Cheetah/Cheetah-2.4.4.tar.gz
Summary  : Cheetah is a template engine and code generation tool.
Group    : Development/Tools
License  : HPND
Requires: Cheetah-bin
Requires: Cheetah-python
Requires: Markdown
BuildRequires : Markdown
BuildRequires : pbr
BuildRequires : pip

BuildRequires : python3-dev
BuildRequires : setuptools

%description
It can be used standalone or combined with other tools and frameworks. Web
        development is its principle use, but Cheetah is very flexible and is also being
        used to generate C++ game code, Java, sql, form emails and even Python code.
        
        Documentation
        ================================================================================
        For a high-level introduction to Cheetah please refer to the User's Guide

%package bin
Summary: bin components for the Cheetah package.
Group: Binaries

%description bin
bin components for the Cheetah package.


%package legacypython
Summary: legacypython components for the Cheetah package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the Cheetah package.


%package python
Summary: python components for the Cheetah package.
Group: Default
Provides: cheetah-python

%description python
python components for the Cheetah package.


%prep
%setup -q -n Cheetah-2.4.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1528573146
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cheetah
/usr/bin/cheetah-analyze
/usr/bin/cheetah-compile

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files python
%defattr(-,root,root,-)
